"""role bindings

Revision ID: f1eac2b1733d
Revises: 36d514380043
Create Date: 2026-09-08 11:40:48.792529
"""

import sqlalchemy as sa
from alembic import op

revision = "f1eac2b1733d"
down_revision = "36d514380043"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=320), nullable=False),
        sa.Column("subject_kind", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject", "role", "scope_type", "scope_id"),
    )
    op.create_index(op.f("ix_role_bindings_org_id"), "role_bindings", ["org_id"], unique=False)
    op.create_index("ix_role_bindings_subject_status", "role_bindings", ["subject", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_role_bindings_subject_status", table_name="role_bindings")
    op.drop_index(op.f("ix_role_bindings_org_id"), table_name="role_bindings")
    op.drop_table("role_bindings")
    # ### end Alembic commands ###
