"""scheduled key rotation

Revision ID: affd47d0342f
Revises: 18cda488c4f0
Create Date: 2026-09-08 16:41:00.224422
"""

import sqlalchemy as sa
from alembic import op

revision = "affd47d0342f"
down_revision = "18cda488c4f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_pickups",
        sa.Column("key_id", sa.UUID(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["key_id"], ["virtual_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("key_id"),
    )
    op.create_index(op.f("ix_key_pickups_expires_at"), "key_pickups", ["expires_at"], unique=False)
    op.add_column("virtual_keys", sa.Column("rotate_every_seconds", sa.Integer(), nullable=True))
    op.add_column("virtual_keys", sa.Column("rotation_grace_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_keys", "rotation_grace_seconds")
    op.drop_column("virtual_keys", "rotate_every_seconds")
    op.drop_index(op.f("ix_key_pickups_expires_at"), table_name="key_pickups")
    op.drop_table("key_pickups")
    # ### end Alembic commands ###
