"""scim provisioning

Revision ID: 4556e45fd362
Revises: affd47d0342f
Create Date: 2026-09-08 16:49:51.913020
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "4556e45fd362"
down_revision = "affd47d0342f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scim_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=True),
        sa.Column("scope_type", sa.String(length=20), nullable=True),
        sa.Column("scope_id", sa.UUID(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_name"),
    )
    op.create_index(op.f("ix_scim_groups_external_id"), "scim_groups", ["external_id"], unique=False)
    op.create_table(
        "scim_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("user_name", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("emails", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_name"),
    )
    op.create_index(op.f("ix_scim_users_external_id"), "scim_users", ["external_id"], unique=False)
    op.create_table(
        "scim_group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["scim_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["scim_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scim_group_members")
    op.drop_index(op.f("ix_scim_users_external_id"), table_name="scim_users")
    op.drop_table("scim_users")
    op.drop_index(op.f("ix_scim_groups_external_id"), table_name="scim_groups")
    op.drop_table("scim_groups")
    # ### end Alembic commands ###
