"""provider invoices

Revision ID: ac6314fc13f9
Revises: 0b94f242d83b
Create Date: 2026-09-08 16:08:46.118868
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "ac6314fc13f9"
down_revision = "0b94f242d83b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("invoice_total", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("ledger_total", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("delta_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_provider"), "invoices", ["provider"], unique=False)
    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("provider_model", sa.String(length=200), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("ledger_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("ledger_prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("ledger_completion_tokens", sa.Integer(), nullable=True),
        sa.Column("ledger_requests", sa.Integer(), nullable=True),
        sa.Column("ledger_ambiguous", sa.Integer(), nullable=True),
        sa.Column("delta_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", "provider_model", "day"),
    )
    op.create_index(op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_invoices_provider"), table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
