"""deployment health queue pressure

Revision ID: 0b94f242d83b
Revises: e1a97b43dd62
Create Date: 2026-09-08 12:56:02.778980
"""

import sqlalchemy as sa
from alembic import op

revision = "0b94f242d83b"
down_revision = "e1a97b43dd62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deployment_health", sa.Column("queue_waiting", sa.Integer(), nullable=True))
    op.add_column("deployment_health", sa.Column("queue_running", sa.Integer(), nullable=True))
    op.add_column("deployment_health", sa.Column("kv_cache_usage", sa.Float(), nullable=True))
    op.add_column("deployment_health", sa.Column("metrics_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deployment_health", "metrics_at")
    op.drop_column("deployment_health", "kv_cache_usage")
    op.drop_column("deployment_health", "queue_running")
    op.drop_column("deployment_health", "queue_waiting")
    # ### end Alembic commands ###
