"""guardrail events

Revision ID: 18cda488c4f0
Revises: ac6314fc13f9
Create Date: 2026-09-08 16:23:51.127770
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "18cda488c4f0"
down_revision = "ac6314fc13f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guardrail_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("key_id", sa.UUID(), nullable=False),
        sa.Column("direction", sa.String(length=4), nullable=False),
        sa.Column("detector", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("categories", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guardrail_events_org_id"), "guardrail_events", ["org_id"], unique=False)
    op.create_index("ix_guardrail_project_created", "guardrail_events", ["project_id", "created_at"], unique=False)
    op.create_index("ix_guardrail_request", "guardrail_events", ["request_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_guardrail_request", table_name="guardrail_events")
    op.drop_index("ix_guardrail_project_created", table_name="guardrail_events")
    op.drop_index(op.f("ix_guardrail_events_org_id"), table_name="guardrail_events")
    op.drop_table("guardrail_events")
    # ### end Alembic commands ###
